#server:
  #port: 8090
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  mvc:
    async:
      request-timeout: 600000
  datasource:
    platform: postgres
    url: jdbc:postgresql://39.98.45.42:5432/gsdb
    username: wanshan
    password: wanshan@2018
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        hbm2ddl.auto: update
    thymeleaf:
      cache: false
logging:
  config: classpath:logback-boot.xml
geoserver:
  url: http://gs.xianyushichuang.com
  username: admin
  passwd: geoserver

