server:
  port: 8090
spring:
  mvc:
    async:
      request-timeout: 600000
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.1.121:5432/renmydb?useUnicode=true&characterEncoding=utf-8&serverTimezone=serverTimezone=Asia/Shanghai
    username: renmy
    password: renmy
    driver-class-name: org.postgresql.Driver
  jackson:
    ##default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      #security:
      #user:
      #name: user
      #password: user

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    auto-mapping-unknown-column-behavior: warning

#mybatis-plus相关配置
mybatis-plus:
  #xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #bean 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cc.wanshan.gis.entity
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator

  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 配置的缓存的全局开关
    cache-enabled: false
    jdbc-type-for-null: null

# geoserver服务配置
geoserver:
  url: http://192.168.1.133:8080/geoserver
  username: wanshan
  passwd: wanshan@gis2019
  postgisHost: 192.168.1.133
  postgisPort: 5432
  postgisUser: postgres
  postgisPassword: wanshan
  postgisDatabase: gsdb

postgis:
  url: jdbc:postgresql://192.168.1.133:5432/gsdb
  user: postgres
  password: wanshan

# swagger 显示判断
swagger:
  enable: true

