server:
  port: 8090
spring:
  mvc:
    async:
      request-timeout: 600000
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.1.133:5432/dev?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=serverTimezone=Asia/Shanghai
    username: postgres
    password: wanshan
    driver-class-name: org.postgresql.Driver
  jackson:
    ##default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        hbm2ddl.auto: update
    thymeleaf:
      cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    auto-mapping-unknown-column-behavior: warning
# geoserver服务配置
geoserver:
  #url: http://192.168.1.133:8080/geoserver
  #username: wanshan
  #passwd: wanshan@gis2019
  url: http://localhost:8080/geoserver
  username: admin
  passwd: geoserver
  postgisHost: 192.168.1.133
  postgisPort: 5432
  postgisUser: postgres
  postgisPassword: wanshan
  postgisDatabase: dev

postgis:
  url: jdbc:postgresql://192.168.1.133:5432/dev
  user: postgres
  password: wanshan
# swagger 显示判断
swagger:
  enable: true

