server:
  port: 8090
  servlet:
    session:
      timeout: 7200
  # salt加密配置
jasypt:
  encryptor:
    password: gis
spring:
  mvc:
    async:
      request-timeout: 600000
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.24.4.12:5432/gis_data?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  # redis配置
  redis:
    host: 172.24.4.11
    password: ENC(BgTB/HJz4yROF14Mf3Se5Q==)
    database: 3
    port: 6379
    timeout: 3S
  data:
    # elasticsearch配置
    elasticsearch:
      cluster-name: gis-application
      hostName: 172.24.4.9
      transport: 9300
      repositories:
        transport:
          tcp:
            connect_timeout: 120s
        enabled: true
  elasticsearch:
    rest:
      uris: ["http://172.24.4.9:9200"]
  security:
    health:
      elasticsearch:
        enabled: false
  jackson:
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期
  #配置spring 上传文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    auto-mapping-unknown-column-behavior: warning
  mapperLocations: classpath*:/mapper/*Mapper.xml

# geoServer服务配置
geoserver:
  url: http://172.24.4.12/geoserver/web
  username: admin
  passwd: geoserver
  postgisHost: 172.24.4.12
  postgisPort: 5432
  postgisUser: admin
  postgisPassword: 123456
  postgisDatabase: gis_data

# postGIS数据库配置
postgis:
  url: jdbc:postgresql://172.24.4.12:5432/gis_data
  user: admin
  password: 123456
  driver-class-name: org.postgresql.Driver

# file 文件路径
file:
  path: D:\Upload

gis:
  # swagger 显示判断
  swagger:
    enable: true
    # token 使用判断
  token:
    jwt: false
    redis: true

# 忽略鉴权url
ignored:
  urls:
    - /user/login/**
    - /user/regist
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico